version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: 
      DATABASE_PORT: 
      DATABASE_USER: 
      DATABASE_PASSWORD: 
      DATABASE_NAME: 
      JWT_SECRET_KEY: 
